### ISSUE TITLE
Screen crash while playing next Aya !

### ISSUE THREAD

**Issue by hgareeballa** [sajidzaman/quranapp#1]
System plays first Ayah, but the page crash when it tries to load the second Ayah !

**Comment by sajidzaman** [comment]
Though the app is available on http://sajidzaman.com/quranapp . Please check and let me know if you face the crash there as well.

**Comment by hgareeballa** [comment]
Nope its working fine in above link,
i have made some changes to the code to work under https only,

please try below link and advise

elmuzamel.com
www.elmuzamel.com

**Comment by hgareeballa** [comment]
Hi
i found the problem, i have updated some of the JS packages in the app to the latest version and that cause the issue !

this is the message i got (Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`)

and i have updated the packages (all of them)

so am not sure now which one was causing the issue !

Regards 
Hassan

**Comment by hgareeballa** [comment]
update packages to lates version
